{% set name = "broh5" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/broh5-{{ version }}.tar.gz
  sha256: 3f6fee7f2ea065690d6669a404093bdec17793ac1e6a6631912f6bf57cd3bcd6
build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python
  entry_points:
    - broh5 = broh5.main:main

requirements:
  host:    
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - numpy >1.21
    - h5py >3.7
    - pillow
    - matplotlib-base
    - nicegui >1.3.16

test:
  imports:
    - broh5
  # commands:
  #   - pip check
  # requires:
  #   - pip

about:
  home: https://github.com/nghia-vo/broh5
  license: Apache-2.0
  license_file: LICENSE
  summary: Browser-based GUI HDF Viewer in Python

extra:
  recipe-maintainers:
    - algotom
