{% set name = "broh5" %}
{% set version = "1.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/broh5-{{ version }}.tar.gz
  sha256: edf195f7fcb5ca0040f517bc31d0500c1aec400d9d84c0164e0bf026bee356cd
build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python
  entry_points:
    - broh5 = broh5.main:main

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - numpy >1.21
    - h5py >3.7
    - hdf5plugin
    - pillow
    - matplotlib-base
    - nicegui >=1.4.21

test:
  requires:
    - python {{ python_min }}
  imports:
    - broh5
  # commands:
  #  - broh5 --version
  # requires:
  #   - pip

about:
  home: https://github.com/algotom/broh5
  license: Apache-2.0
  license_file: LICENSE
  summary: Browser-based GUI HDF Viewer in Python
  doc_url: https://broh5.readthedocs.io/

extra:
  recipe-maintainers:
    - nghia-vo
