{% set name = "broh5" %}
{% set version = "1.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/broh5-{{ version }}.tar.gz
  sha256: ceb1d4587c91aa036b78219f18a6b5de8a42f5bc41ed98b64124e85be37eb6f2
build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python
  entry_points:
    - broh5 = broh5.main:main

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - numpy >1.21
    - h5py >3.7
    - hdf5plugin
    - pillow
    - matplotlib-base
    - nicegui >=1.4.21,<2.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - broh5

about:
  home: https://github.com/algotom/broh5
  license: Apache-2.0
  license_file: LICENSE
  summary: Browser-based GUI HDF Viewer in Python
  doc_url: https://broh5.readthedocs.io/

extra:
  recipe-maintainers:
    - nghia-vo
