{% set name = "broh5" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/broh5-{{ version }}.tar.gz
  sha256: 23467fabe11c6f5a0746ba0b88f44df3e1c7532be792c082b5ca9cb6e86c2565
build:
  number: 2
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python
  entry_points:
    - broh5 = broh5.main:main

requirements:
  host:    
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - numpy >1.21
    - h5py >3.7
    - hdf5plugin
    - pillow
    - matplotlib-base
    - nicegui >1.3.16

test:
  imports:
    - broh5
  # commands:
  #  - broh5 --version
  # requires:
  #   - pip

about:
  home: https://github.com/algotom/broh5
  license: Apache-2.0
  license_file: LICENSE
  summary: Browser-based GUI HDF Viewer in Python

extra:
  recipe-maintainers:
    - algotom
    - nghia-vo
    
