{% set name = "broh5" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/broh5-{{ version }}.tar.gz
  sha256: 8a6aff6ecb225ed70f84f785e2d9b40ce61b40ae839f654e8ca2020b412badac
build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python
  entry_points:
    - broh5 = broh5.main:main

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - numpy >1.21
    - h5py >3.7
    - hdf5plugin
    - pillow
    - matplotlib-base
    - nicegui >1.4.5

test:
  imports:
    - broh5
  # commands:
  #  - broh5 --version
  # requires:
  #   - pip

about:
  home: https://github.com/algotom/broh5
  license: Apache-2.0
  license_file: LICENSE
  summary: Browser-based GUI HDF Viewer in Python
  doc_url: https://broh5.readthedocs.io/

extra:
  recipe-maintainers:
    - nghia-vo

